### ISSUE TITLE
Gitter Room!?

### ISSUE THREAD

**Issue by willhoag** [vangularjs/vangularjs-meetup-july-16-2014#1]
Would be great to have a [Gitter](https://gitter.im/) chat room associated with this github organization so the community can stay lively in-between meetups! You could attach one to a repo called discussion or chat or something.

![typing gif](http://i.giphy.com/YhyAJUCpno53y.gif)

**Comment by garbles** [comment]
Good idea. Done. https://gitter.im/vangularjs/chat

**Comment by willhoag** [comment]
Awesome! I'll pop in soon. In the mean time, we could add a README.md with a Gitter badge in case someone stumbles upon the repo. I'd do a pull request, but can't fork an uninitialized repo...

[![Gitter chat](https://badges.gitter.im/vangularjs/chat.png)](https://gitter.im/vangularjs/chat)

Here is a blog post about the badge syntax:
http://blog.gitter.im/badgers/

**Comment by garbles** [comment]
@willhoag https://github.com/vangularjs/chat/tree/master
